// Code generated by design/cmd/gentokens from design/tokens.json; DO NOT EDIT.

package workspace

import "gioui.org/unit"

// Colors, by semantic role.
var (
	colInk         = rgb(0x111111)
	colBody        = rgb(0x374151)
	colMuted       = rgb(0x6b7280)
	colFaint       = rgb(0x9ca3af)
	colCanvas      = rgb(0xffffff)
	colSoft        = rgb(0xf8f9fa)
	colCard        = rgb(0xf5f5f5)
	colHover       = rgb(0xeceef1)
	colHair        = rgb(0xe5e7eb)
	colHairSoft    = rgb(0xf0f1f3)
	colLine        = rgb(0xd4d4d8)
	colLineStrong  = rgb(0xa1a1aa)
	colBackdrop    = rgb(0xd9dbe0)
	colDark        = rgb(0x101010)
	colOnDark      = rgb(0xffffff)
	colOnDarkBody  = rgb(0xd4d4d8)
	colOnDarkMuted = rgb(0xa1a1aa)
	colOk          = rgb(0x15803d)
	colOkBg        = rgb(0xdcfce7)
	colOkSolid     = rgb(0x16a34a)
	colWarn        = rgb(0xb45309)
	colWarnBg      = rgb(0xfef3c7)
	colWarnSolid   = rgb(0xf59e0b)
	colErr         = rgb(0xb91c1c)
	colErrBg       = rgb(0xfee2e2)
	colErrTint     = rgb(0xfffafa)
	colErrSolid    = rgb(0xdc2626)
	colAccent      = rgb(0x3b82f6)
	colAccentBg    = rgb(0xeff6ff)
	colAccentMd    = rgb(0xbfdbfe)
	colHighlight   = rgb(0xfef9c3)
)

// Translucent overlays.
var (
	colScrim       = alpha(rgb(0x000000), 84)
	colScrimStrong = alpha(rgb(0x111111), 224)
)

// Font sizes: design size x density 1.04, rounded to 0.5sp.
const (
	fsMicro   unit.Sp = 11
	fsCaption unit.Sp = 11.5
	fsSmall   unit.Sp = 12
	fsBody    unit.Sp = 13
	fsTitle   unit.Sp = 16.5
	fsDisplay unit.Sp = 18.5
)

// Corner radii.
const (
	radiusXs   unit.Dp = 3
	radiusSm   unit.Dp = 6
	radiusMd   unit.Dp = 8
	radiusLg   unit.Dp = 10
	radiusPill unit.Dp = 999
)
